### ISSUE TITLE
RequiredError does not fire

### ISSUE THREAD

**Issue by jezile** [csuka1219/CleaveMudDateMask#1]
It always fires default 'Not a valid date time' message.

**Comment by csuka1219** [comment]
Can you paste your code here, if I set the value of the "ErrorText" parameter it overwrites the default "Not a valid date time" message.

**Comment by jezile** [comment]
Yes, you are right. I was using RequiredError parameter instead of ErrorText. It works now. Thanks! Great repo BTW!
