### ISSUE TITLE
What's the purpose of setting "data-muddate" in UserAttributes ?

### ISSUE THREAD

**Issue by hybrid2102** [csuka1219/CleaveMudDateMask#2]
What's the purpose of setting "data-muddate" in UserAttributes ?

As seen in:
https://github.com/csuka1219/CleaveMudDateMask/blob/6b3892510bd344a6891b1ffdf2d59d7740e69ee0/CleaveMudDateMask/Component/MudDateField.cs#L16

PS: thanks for the useful repo!

Thanks!

**Comment by csuka1219** [comment]
I'm happy you found it useful.
To be honest I don't remember, I guess its a unnecessary line left over to get Cleave.js working.
You can ignore it.
